### ISSUE TITLE
gcc4 pointer patch

### ISSUE THREAD

**Issue by polluks** [jens-maus/libopenurl#1]
popport.c:236: error: invalid operands to binary - (have 'TEXT ' and 'STRPTR')

<pre>--- prefs/popport.c.bak	2015-08-26 20:26:09 +0000
+++ prefs/popport.c	2015-09-02 16:20:31 +0000
@@ -233,7 +233,7 @@
 
                 if (dot)
                 {
-                    strlcpy(buf, port, dot-port);
+                    strlcpy(buf, port, (STRPTR)dot-port);
                     port = buf;
                 }
         }
</pre>

**Comment by jens-maus** [comment]
First of all thanks for your patch! Great to see amiga people are starting to use github. 

However, I would really prefer if you could create a real pull request rather than submitting your changes in sinple diff format. This would make everything more easy and the way github should be used. So please create a pull request!
